import type { CommonMonster, Race, Element, EffectType } from "../cards";

const createCommonMonster = (property: {
    card_name: string;
    monster_type: "効果モンスター" | "通常モンスター" | "儀式モンスター";
    level: number;
    element: Element;
    race: Race;
    attack: number;
    defense: number;
    text: string;
    image: string;
    effect: EffectType;
    canNormalSummon: boolean;
}): CommonMonster => {
    return {
        ...property,
        card_type: "モンスター",
        hasDefense: true,
        hasLevel: true,
        hasRank: false,
        hasLink: false,
    };
};

export const COMMON_MONSTERS = [
    createCommonMonster({
        card_name: "封印されしエクゾディア",
        monster_type: "効果モンスター",
        level: 3,
        element: "闇",
        race: "魔法使い",
        attack: 1000,
        defense: 1000,
        text: "このカードと「封印されし者の右腕」「封印されし者の左腕」「封印されし者の右足」「封印されし者の左足」が手札に全て揃った時、自分はデュエルに勝利する。",
        image: "card100224614_1.jpg",
        effect: {},
        canNormalSummon: true,
    }),
    createCommonMonster({
        card_name: "封印されし者の右腕",
        monster_type: "通常モンスター",
        level: 1,
        element: "闇",
        race: "魔法使い",
        attack: 200,
        defense: 300,
        text: "「封印されしエクゾディア」と組み合わせることで真の力を発揮する封印されし右腕。",
        image: "card100220676_1.jpg",
        effect: {},
        canNormalSummon: true,
    }),
    createCommonMonster({
        card_name: "封印されし者の左腕",
        monster_type: "通常モンスター",
        level: 1,
        element: "闇",
        race: "魔法使い",
        attack: 200,
        defense: 300,
        text: "「封印されしエクゾディア」と組み合わせることで真の力を発揮する封印されし左腕。",
        image: "card100220667_1.jpg",
        effect: {},
        canNormalSummon: true,
    }),
    createCommonMonster({
        card_name: "封印されし者の右足",
        monster_type: "通常モンスター",
        level: 1,
        element: "闇",
        race: "魔法使い",
        attack: 200,
        defense: 300,
        text: "「封印されしエクゾディア」と組み合わせることで真の力を発揮する封印されし右足。",
        image: "card100014919_1.jpg",
        effect: {},
        canNormalSummon: true,
    }),
    createCommonMonster({
        card_name: "封印されし者の左足",
        monster_type: "通常モンスター",
        level: 1,
        element: "闇",
        race: "魔法使い",
        attack: 200,
        defense: 300,
        text: "「封印されしエクゾディア」と組み合わせることで真の力を発揮する封印されし左足。",
        image: "card100014920_1.jpg",
        effect: {},
        canNormalSummon: true,
    }),
    createCommonMonster({
        card_name: "ジェネクス・コントローラー",
        monster_type: "通常モンスター",
        level: 3,
        element: "闇",
        race: "機械",
        attack: 1400,
        defense: 1200,
        text: "仲間達と心を通わせる事ができる、数少ないジェネクスのひとり。様々なエレメントの力をコントロールできるぞ。",
        image: "card100004619_1.jpg",
        effect: {},
        canNormalSummon: true,
    }),
    createCommonMonster({
        card_name: "大砲だるま",
        monster_type: "通常モンスター",
        level: 2,
        element: "闇",
        race: "機械",
        attack: 900,
        defense: 500,
        text: "大砲で埋め尽くされているメカだるま。ねらいは外さない。",
        image: "card100224572_1.jpg",
        effect: {},
        canNormalSummon: true,
    }),
    createCommonMonster({
        card_name: "神聖なる魂",
        monster_type: "効果モンスター",
        level: 6,
        element: "光",
        race: "天使",
        attack: 2000,
        defense: 1800,
        text: "このカードは通常召喚できない。\n自分の墓地から光属性モンスター２体を除外した場合に特殊召喚できる。(1)：このカードがモンスターゾーンに存在する限り、相手フィールドのモンスターの攻撃力は、相手バトルフェイズの間３００ダウンする。",
        image: "card100177659_1.jpg",
        effect: {},
        canNormalSummon: false,
    }),
    createCommonMonster({
        card_name: "クリッター",
        monster_type: "効果モンスター",
        level: 3,
        element: "闇",
        race: "悪魔",
        attack: 1000,
        defense: 600,
        text: "このカード名の効果は1ターンに1度しか使用できない。①：このカードがフィールドから墓地へ送られた場合に発動する。デッキから攻撃力1500以下のモンスター1体を手札に加える。このターン、自分はこの効果で手札に加えたカード及びその同名カードの発動ができない。",
        image: "card100350408_1.jpg",
        effect: {},
        canNormalSummon: true,
    }),
    createCommonMonster({
        card_name: "宣告者の神巫",
        monster_type: "効果モンスター",
        level: 2,
        element: "光",
        race: "天使",
        attack: 500,
        defense: 300,
        text: "このカード名の①②の効果はそれぞれ1ターンに1度しか使用できない。①：このカードが召喚・特殊召喚に成功した場合に発動できる。デッキ・EXデッキから天使族モンスター1体を墓地へ送る。このカードのレベルはターン終了時まで、そのモンスターのレベル分だけ上がる。②：このカードがリリースされた場合に発動できる。手札・デッキから「宣告者の神巫」以外のレベル2以下の天使族モンスター1体を特殊召喚する。",
        image: "card100186167_1.jpg",
        effect: {},
        canNormalSummon: true,
    }),
    createCommonMonster({
        card_name: "竜輝巧－エルγ",
        monster_type: "効果モンスター",
        level: 1,
        element: "光",
        race: "機械",
        attack: 2000,
        defense: 0,
        text: "このカードは通常召喚できず、「ドライトロン」カードの効果でのみ特殊召喚できる。このカード名の効果は1ターンに1度しか使用できない。①：自分の手札・フィールドから、このカード以外の「ドライトロン」モンスターまたは儀式モンスター1体をリリースして発動できる。このカードを手札・墓地から守備表示で特殊召喚する。その後、自分の墓地から「竜輝巧－エルγ」以外の攻撃力2000の「ドライトロン」モンスター1体を選んで特殊召喚できる。この効果を発動するターン、自分は通常召喚できないモンスターしか特殊召喚できない。",
        image: "card100206513_1.jpg",
        effect: {},
        canNormalSummon: false,
    }),
    createCommonMonster({
        card_name: "竜輝巧－アルζ",
        monster_type: "効果モンスター",
        level: 1,
        element: "光",
        race: "機械",
        attack: 2000,
        defense: 0,
        text: "このカードは通常召喚できず、「ドライトロン」カードの効果でのみ特殊召喚できる。このカード名の効果は1ターンに1度しか使用できない。①：このカード以外の自分の手札・フィールドの、「ドライトロン」モンスターか儀式モンスター1体をリリースして発動できる（この効果を発動するターン、自分は通常召喚できないモンスターしか特殊召喚できない）。このカードを手札・墓地から守備表示で特殊召喚する。その後、デッキから儀式魔法カード1枚を手札に加えることができる。",
        image: "card100206525_1.jpg",
        effect: {},
        canNormalSummon: false,
    }),
    createCommonMonster({
        card_name: "竜輝巧－バンα",
        monster_type: "効果モンスター",
        level: 1,
        element: "光",
        race: "機械",
        attack: 2000,
        defense: 0,
        text: "このカードは通常召喚できず、「ドライトロン」カードの効果でのみ特殊召喚できる。このカード名の効果は1ターンに1度しか使用できない。①：このカード以外の自分の手札・フィールドの、「ドライトロン」モンスターか儀式モンスター1体をリリースして発動できる（この効果を発動するターン、自分は通常召喚できないモンスターしか特殊召喚できない）。このカードを手札・墓地から守備表示で特殊召喚する。その後、デッキから儀式モンスター1枚を手札に加えることができる。",
        image: "card100206504_1.jpg",
        effect: {},
        canNormalSummon: false,
    }),
    createCommonMonster({
        card_name: "サイバー・エンジェル－弁天－",
        monster_type: "儀式モンスター",
        level: 6,
        element: "光",
        race: "天使",
        attack: 1800,
        defense: 1500,
        text: "「機械天使の儀式」により降臨。①：このカードが戦闘でモンスターを破壊し墓地へ送った場合に発動する。そのモンスターの元々の守備力分のダメージを相手に与える。②：このカードがリリースされた場合に発動できる。デッキから天使族・光属性モンスター１体を手札に加える。",
        image: "card100035806_1.jpg",
        effect: {},
        canNormalSummon: false,
    }),
    createCommonMonster({
        card_name: "サイバー・エンジェル－韋駄天－",
        monster_type: "儀式モンスター",
        level: 6,
        element: "光",
        race: "天使",
        attack: 1600,
        defense: 2000,
        text: "「機械天使の儀式」により降臨。①：このカードが儀式召喚に成功した場合に発動できる。自分のデッキ・墓地から儀式魔法カード１枚を選んで手札に加える。②：このカードがリリースされた場合に発動できる。自分フィールドの全ての儀式モンスターの攻撃力・守備力は１０００アップする。",
        image: "card100133121_1.jpg",
        effect: {},
        canNormalSummon: false,
    }),
] satisfies CommonMonster[];
